sudo: false
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - '12'
  - '10'
  - '8'
  - '6'
  - '4'
  - '0.12'
  - '0.10'
jobs:
  exclude:
      - node-js: 0.10
        arch: ppc64le
      - node-js: 0.12
        arch: ppc64le
after_script:
  - npm run coveralls
